config/routes.rb
Rails.application.routes.draw do
  resources :patients
  devise_for :users
  root 'home#index'
  get 'home/users'
  get 'home/index'
  get 'home/my_patients' => "home#my_patients"
  get 'patients/:id/edit_all' => "patients#edit_all", as: 'patient_edit_all'
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def users
    @users = User.all
  end
  
  def my_patients
    if user_signed_in?
      @my_patients = User.find_by(id: current_user.id)
    end
    
    
      
  end
  
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end
  
  def edit_all
    @patient = Patient.find(params[:id])
  end
  

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to edit_patient_path(@patient.id)}#, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end
# edit_patient_path(patient.id)
  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to edit_patient_path(@patient.id)}#@patient#, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :age, :address, :weight, :gender, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/_flash_alerts.html.erb
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

app/views/home/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Model Testing", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Add Patient", new_patient_path %></li>
          <li><%= link_to "Show Patients", patients_path %></li>
          <li><%= link_to "My Patients", home_my_patients_path %></li>
          <li><%# link_to "Show All Tweets", tweets_path %></li>
          <li><%# link_to "New Tweet", new_tweet_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <li><%= link_to "List Users", home_users_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_voice_stuff.html.erb
 <style>
  .speech {border: 1px solid #DDD; width: 300px; padding: 0; margin: 0}
  .speech input {border: 0; width: 240px; display: inline-block; height: 40px;}
  .speech img {float: right; width: 40px }
</style>
  
<script>


function speak(text) {
    var msg = new SpeechSynthesisUtterance();
    var voices = speechSynthesis.getVoices();
    msg.voice = voices[10];
    msg.voiceURI = 'native';
    msg.volume = 1;
    msg.rate = 1;
    msg.pitch = 2;
    msg.text = text;
    msg.lang = 'en-US';

    speechSynthesis.speak(msg);
    
}

speak('<%= yield(:speaker) %>');

setTimeout(startDictation, 1000)


function startDictation() {
 
    if (window.hasOwnProperty('webkitSpeechRecognition')) {
 
      var recognition = new webkitSpeechRecognition();
 
      recognition.continuous = true;
      recognition.interimResults = false;
 
      recognition.lang = "en-US";
      recognition.start();
 
      recognition.onresult = function(e) {
        document.getElementById('transcript').value
                                 = e.results[0][0].transcript;
        setTimeout(recognition.stop, 100000)
        //recognition.stop();
        document.getElementById('labnol').submit();
      };
 
      recognition.onerror = function(e) {
        recognition.stop();
      }
 
    }
  }

</script>

app/views/home/index.html.erb
Hello World!

app/views/home/my_patients.html.erb
<% if user_signed_in? %>

<h1>My Patients</h1>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Address</th>
        <th>Weight</th>
        <th>Gender</th>
        <th>Patient ID</th>
        <th>Actions</th>
    </thead>
    
    <% @my_patients.patient.each do |patient| %>
    <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.address %></td>
        <td><%= patient.weight %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.id %></td>
        <td><%= link_to 'Show', patient_path(patient.id), class: 'btn btn-primary btn-xs' %>
        <%= link_to 'Edit', edit_patient_path(patient.id), class: 'btn btn-success btn-xs' %>
        <%= link_to 'Edit All', patient_edit_all_path(patient.id), class: 'btn btn-success btn-xs' %>
        <%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
        
    </tr>
    
    <% end %>

</table>
<% else %>

Must Be Signed In To View This Page...
<% end %>

app/views/home/users.html.erb
<h2>Users With Patients</h2>

<% @users.each do |user| %>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
        <th colspan="2"><h4>
           Username: <%= user.user_name %> - <%= user.email %> 
        </h4></th>
    </tr>
    <tr>
      <th>Patient Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>    
    
    
    
    <% user.patient.each do |patient| %>
        <tr>
        <td><%= patient.first_name %> <%= patient.last_name %></td>
        
        <td>
            <%= link_to 'Show', patient, class: 'btn btn-default btn-xs' %>
            <%= link_to 'Edit', edit_patient_path(patient), class: 'btn btn-info btn-xs' %>
            <%= link_to 'Edit All', patient_edit_all_path(patient.id), class: 'btn btn-success btn-xs' %>
            <%= link_to 'Delete Patient', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
        
    <% end %>
    </tr>
    
<br/><br/>
<% end %>
    </tbody>
</table>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render "home/nav" %>
<div class="container">
  <%= render "home/flash_alerts" %>
  <%= yield %>
</div>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient, html: {id: 'labnol'}) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="speech">
  <% if !@patient.first_name? %>  
      <% f.label :first_name %><% content_for :speaker, "First Name" %>
      <%= f.text_field :first_name, id: 'transcript', placeholder: " First Name" %>
    
    
  
  <% elsif !@patient.last_name? %>
      <% f.label :last_name %><% content_for :speaker, "Last Name" %>
      <%= f.text_field :last_name, id: 'transcript', placeholder: " Last Name" %>
    
  
  <% elsif !@patient.age? %>
      <% f.label :age %><% content_for :speaker, "Age" %>
      <%= f.number_field :age, class: 'form-control', id: 'transcript', placeholder: " Age" %>
    
  
  <% elsif !@patient.address? %>      
      <% f.label :address %><% content_for :speaker, "Address" %>
      <%= f.text_field :address, class: 'form-control', id: 'transcript', placeholder: " Address" %>
    
  <% elsif !@patient.weight? %>  
      <% f.label :weight %><% content_for :speaker, "Weight in Pounds" %>
      <%= f.text_field :weight, class: 'form-control', id: 'transcript', placeholder: " Weight" %>
    
    
  <% elsif !@patient.gender? %>  
      <% f.label :gender %><% content_for :speaker, "Gender" %>
      <%= f.text_field :gender, class: 'form-control', id: 'transcript', placeholder: " Gender" %>
    
  
  <% end %>
  
  <% if user_signed_in? %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  
  <img onclick="startDictation()" src="//i.imgur.com/cHidSVu.gif" />
    </div>
    <br/><br/>
  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

<%= render 'home/voice_stuff' %>

app/views/patients/_form_all.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
  
    
  

    <div class="form-group">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  

    <div class="form-group">
      <%= f.label :age %><br>
      <%= f.number_field :age, class: 'form-control' %>
    </div>
  

    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    

    <div class="form-group">
      <%= f.label :weight %><br>
      <%= f.text_field :weight, class: 'form-control' %>
    </div>
    

    <div class="form-group">
      <%= f.label :gender %><br>
      <%= f.text_field :gender, class: 'form-control' %>
    </div>
  

  
  <% if user_signed_in? %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Patient</h3>
  </div>
  <div class="panel-body">
    

<%= render 'form' %>

</div>
    <div class="panel-footer">
        <%= link_to 'Show', @patient %> | <%= link_to 'Back', patients_path %>
    </div>
</div>

app/views/patients/edit_all.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Patient</h3>
  </div>
  <div class="panel-body">
    


<%= render 'form_all' %>

</div>
    <div class="panel-footer">
        <%= link_to 'Show', @patient %> | <%= link_to 'Back', patients_path %>
    </div>
</div>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing All Patients</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Weight</th>
      <th>Gender</th>
      <th>Nurse</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.address %></td>
        <td><%= patient.weight %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.user.user_name %></td>
        <td><%= link_to 'Show', patient, class: 'btn btn-default btn-xs' %>
        <%= link_to 'Edit', edit_patient_path(patient), class: 'btn btn-default btn-xs' %>
        <%= link_to 'Edit All', patient_edit_all_path(patient.id), class: 'btn btn-default btn-xs' %>
        <%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Patient', new_patient_path %>

app/views/patients/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Patient</h3>
  </div>
  <div class="panel-body">

<%= render 'form' %>

</div>
    <div class="panel-footer">
        <%= link_to 'Back', patients_path %>
    </div>
</div>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @patient.weight %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<%= link_to 'Edit Voice', edit_patient_path(@patient.id), class: 'btn btn-primary btn-xs' %> 
<%= link_to 'Edit All', patient_edit_all_path(@patient.id), class: 'btn btn-info btn-xs' %>
<%= link_to 'Back', patients_path, class: 'btn btn-primary btn-xs' %>